[project]
name = "hipscat"
license = {file = "LICENSE"}
readme = "README.md"

classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
]
dynamic = ["version"]

requires-python = ">=3.8"
dependencies = [
    "healpy",
    "pandas",
    "setuptools_scm",
]

# On a mac, install optional dependencies with `pip install '.[dev]'` (include the single quotes)
[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov", # Used to report total code coverage
    "pre-commit", # Used to run checks before finalizing a git commit
    "nbconvert", # Needed for pre-commit check to clear output from Python notebooks
    "pylint", # Used for static linting of files
]

[metadata]
description = "Hierarchical Progressive Survey Catalog"
long_description = { file = "README.md" }
url = "https://github.com/astronomy-commons/hipscat"

[build-system]
requires = ["setuptools","wheel"]
build-backend = "setuptools.build_meta"

[tool.pylint.'MESSAGES CONTROL']
disable = """
    missing-module-docstring,
"""
