[project]
name = "hipscat"
license = {file = "LICENSE"}
readme = "README.md"

classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
]
version = "0.0.1"

requires-python = ">=3.8"
dependencies = [
    "healpy",
    "pandas",
]

# On a mac, install optional dependencies with `pip install '.[dev]'` (include the single quotes)
[project.optional-dependencies]
dev = [
    "pytest", 
    "pytest-cov",
]

[metadata]
description = "Hierarchical Progressive Survey Catalog"
long_description = { file = "README.md" }
url = "https://github.com/astronomy-commons/hipscat"

[build-system]
requires = ["setuptools","wheel"]
build-backend = "setuptools.build_meta"
